// Copyright 2021 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Author: Florian Zaruba <zarubaf@iis.ee.ethz.ch>
//         Fanchen Kong <fanchen.kong@kuleuven.be>
// AUTOMATICALLY GENERATED by genoccamy.py; edit the script instead.

// This file holds cva6 (host) + ara (simd) modules
`include "axi/typedef.svh"
`include "ara/intf_typedef.svh"
module ${name}_cva6_ara import ${name}_pkg::*; (
  input  logic              clk_i,
  input  logic              rst_ni,
  input  chip_id_t          chip_id_i,
  input  logic [1:0]        irq_i,
  input  logic              ipi_i,
  input  logic              time_irq_i,
  input  logic              debug_req_i,
  input  logic [${occamy_cfg["addr_width"]-1}:0]       boot_addr_i,
  output ${soc_narrow_xbar.in_cva6.req_type()} axi_req_o,
  input  ${soc_narrow_xbar.in_cva6.rsp_type()} axi_resp_i
);

  // Internal types for cva6 and ara
  // Since they share the axi mux, their axi types are the same
  localparam Cva6AraAxiAddrWidth = ${soc_narrow_xbar.in_cva6.aw};
  localparam Cva6AraAxiDataWidth = ${soc_narrow_xbar.in_cva6.dw};
  localparam Cva6AraAxiStrbWidth = Cva6AraAxiDataWidth/8;
  localparam Cva6AraAxiIdWidth   = ${soc_narrow_xbar.in_cva6.iw}-1; // The extra -1 is for two slv ports
  localparam Cva6AraAxiUserWidth = ${soc_narrow_xbar.in_cva6.uw};
  typedef logic [Cva6AraAxiAddrWidth-1:0] cva6_ara_addr_t;
  typedef logic [Cva6AraAxiDataWidth-1:0] cva6_ara_data_t;
  typedef logic [Cva6AraAxiStrbWidth-1:0] cva6_ara_strb_t;
  typedef logic [Cva6AraAxiIdWidth-1:0]   cva6_ara_id_t; 
  typedef logic [Cva6AraAxiUserWidth-1:0] cva6_ara_user_t;
  `AXI_TYPEDEF_ALL(cva6_ara_axi,cva6_ara_addr_t,cva6_ara_id_t,cva6_ara_data_t,cva6_ara_strb_t,cva6_ara_user_t)

  cva6_ara_axi_req_t  cva6_axi_req, ara_axi_req, ara_axi_req_inval;
  cva6_ara_axi_resp_t cva6_axi_resp, ara_axi_resp, ara_axi_resp_inval;

  logic [1:0]        irq;
  logic              ipi;
  logic              time_irq;
  logic              debug_req;
  logic [63:0]       cva6_boot_addr;
  always_comb begin
      cva6_boot_addr = {${64-occamy_cfg["addr_width"]}'h0, boot_addr_i};
  end
  sync #(.STAGES (2))
    i_sync_debug (.clk_i, .rst_ni, .serial_i (debug_req_i), .serial_o (debug_req));
  sync #(.STAGES (2))
    i_sync_ipi  (.clk_i, .rst_ni, .serial_i (ipi_i), .serial_o (ipi));
  sync #(.STAGES (2))
    i_sync_time_irq  (.clk_i, .rst_ni, .serial_i (time_irq_i), .serial_o (time_irq));
  sync #(.STAGES (2))
    i_sync_irq_0  (.clk_i, .rst_ni, .serial_i (irq_i[0]), .serial_o (irq[0]));
  sync #(.STAGES (2))
    i_sync_irq_1  (.clk_i, .rst_ni, .serial_i (irq_i[1]), .serial_o (irq[1]));

  //////////////
  // AXI MUX ///
  //////////////
  axi_mux #(
    .SlvAxiIDWidth(Cva6AraAxiIdWidth              ), 
    .slv_ar_chan_t(cva6_ara_axi_ar_chan_t         ),
    .slv_aw_chan_t(cva6_ara_axi_aw_chan_t         ),
    .slv_b_chan_t (cva6_ara_axi_b_chan_t          ),
    .slv_r_chan_t (cva6_ara_axi_r_chan_t          ),
    .slv_req_t    (cva6_ara_axi_req_t             ),
    .slv_resp_t   (cva6_ara_axi_resp_t            ),
    .mst_ar_chan_t(${soc_narrow_xbar.in_cva6.ar_chan_type()}  ),
    .mst_aw_chan_t(${soc_narrow_xbar.in_cva6.aw_chan_type()}  ),
    .w_chan_t     (${soc_narrow_xbar.in_cva6.w_chan_type()}   ),
    .mst_b_chan_t (${soc_narrow_xbar.in_cva6.b_chan_type()}   ),
    .mst_r_chan_t (${soc_narrow_xbar.in_cva6.r_chan_type()}   ),
    .mst_req_t    (${soc_narrow_xbar.in_cva6.req_type()}      ),
    .mst_resp_t   (${soc_narrow_xbar.in_cva6.rsp_type()}      ),
    .NoSlvPorts   (2                ),
    .SpillAr      (1'b1             ),
    .SpillR       (1'b1             ),
    .SpillAw      (1'b1             ),
    .SpillW       (1'b1             ),
    .SpillB       (1'b1             )
  ) i_system_mux (
    .clk_i      (clk_i                                ),
    .rst_ni     (rst_ni                               ),
    .test_i     (1'b0                                 ),
    .slv_reqs_i ({ara_axi_req_inval, cva6_axi_req}    ),
    .slv_resps_o({ara_axi_resp_inval, cva6_axi_resp}  ),
    .mst_req_o  (axi_req_o                            ),
    .mst_resp_i (axi_resp_i                           )
  );

  ///////////
  // CVA6 ///
  ///////////

  // Memory regions
  localparam logic [63:0] WideSPMBase           =   ${util.to_sv_hex(occamy_cfg["spm_wide"]["address"], 64)};
  localparam logic [63:0] WideSPMLength         =   ${util.to_sv_hex(occamy_cfg["spm_wide"]["length"], 64)};
  localparam logic [63:0] NarrowSPMBase         =   ${util.to_sv_hex(occamy_cfg["spm_narrow"]["address"], 64)};
  localparam logic [63:0] NarrowSPMLength       =   ${util.to_sv_hex(occamy_cfg["spm_narrow"]["length"], 64)};
  localparam logic [63:0] BootromBase           =   ${util.to_sv_hex(occamy_cfg["peripherals"]["rom"]["address"], 64)};
  localparam logic [63:0] BootromLength         =   ${util.to_sv_hex(occamy_cfg["peripherals"]["rom"]["length"], 64)};
  localparam logic [63:0] DebugBase             =   64'd0;
  localparam logic [63:0] DebugLength           =   64'd4096;
  // MMIO regions
  localparam logic [63:0] SoCPeriphBase         =   64'd0;
  localparam logic [63:0] SoCPeriphLength       =   ${util.to_sv_hex(cluster_base_addr, 64)};
  localparam logic [63:0] ClusterBase           =   ${util.to_sv_hex(cluster_base_addr, 64)};
  localparam logic [63:0] ClusterLength         =   ${util.to_sv_hex(cluster_base_offset, 64)};

  /////////////////////////
  // CVA6 Configurations //
  /////////////////////////
  localparam CVA6ConfigXlen = 64;

  localparam CVA6ConfigNrCommitPorts = 2;
  // We do not need the FPU in CVA6, the FPU is offloaded to the Ara
  localparam CVA6ConfigRVF = 0;
  localparam CVA6ConfigRVD = 0;
  localparam CVA6ConfigF16En = 0;
  localparam CVA6ConfigF16AltEn = 0;
  localparam CVA6ConfigF8En = 0;
  localparam CVA6ConfigF8AltEn = 0;
  localparam CVA6ConfigFVecEn = 0;

  localparam CVA6ConfigCvxifEn = 0;   
  localparam CVA6ConfigCExtEn = 1;    // Compress Ext
  localparam CVA6ConfigZcbExtEn = 0;  
  localparam CVA6ConfigZcmpExtEn = 0; 
  localparam CVA6ConfigAExtEn = 1;    // Atomic Ext
  localparam CVA6ConfigBExtEn = 0;    
  localparam CVA6ConfigHExtEn = 0;    
  localparam CVA6ConfigVExtEn = 1;    // Vector Ext
  localparam CVA6ConfigRVZiCond = 0;
  localparam CVA6ConfigSclicExtEn = 0;
  localparam CVA6ConfigXhclicExtEn = 0;  

  localparam CVA6ConfigAxiIdWidth   = Cva6AraAxiIdWidth;
  localparam CVA6ConfigAxiAddrWidth = Cva6AraAxiAddrWidth;
  localparam CVA6ConfigAxiDataWidth = Cva6AraAxiDataWidth;
  localparam CVA6ConfigFetchUserEn  = 0;
  localparam CVA6ConfigFetchUserWidth = CVA6ConfigXlen; 
  localparam CVA6ConfigDataUserEn = 0;
  localparam CVA6ConfigDataUserWidth = CVA6ConfigXlen;

  localparam CVA6ConfigIcacheByteSize = 4096;
  localparam CVA6ConfigIcacheSetAssoc = 4;
  localparam CVA6ConfigIcacheLineWidth = 128;
  localparam CVA6ConfigDcacheByteSize = 8192;
  localparam CVA6ConfigDcacheSetAssoc = 4;
  localparam CVA6ConfigDcacheLineWidth = 256;

  localparam CVA6ConfigDcacheFlushOnFence = 1'b0;
  localparam CVA6ConfigDcacheInvalidateOnFlush = 1'b0;

  localparam CVA6ConfigDcacheIdWidth = 1;
  localparam CVA6ConfigMemTidWidth = 2;

  localparam CVA6ConfigWtDcacheWbufDepth = 8;

  localparam CVA6ConfigNrScoreboardEntries = 8;

  localparam CVA6ConfigNrLoadPipeRegs = 1;
  localparam CVA6ConfigNrStorePipeRegs = 0;
  localparam CVA6ConfigNrLoadBufEntries = 2;

  localparam CVA6ConfigRASDepth = 2;
  localparam CVA6ConfigBTBEntries = 32;
  localparam CVA6ConfigBHTEntries = 128;

  localparam CVA6ConfigTvalEn = 1;

  localparam CVA6ConfigNrPMPEntries = 8;

  localparam CVA6ConfigPerfCounterEn = 0;

  localparam config_pkg::cache_type_t CVA6ConfigDcacheType = config_pkg::WT;

  localparam CVA6ConfigMmuPresent = 0;

  localparam CVA6ConfigRvfiTrace = 1;

  localparam config_pkg::cva6_user_cfg_t cva6_user_cfg = '{
      XLEN: unsigned'(CVA6ConfigXlen),
      VLEN: unsigned'(64),
      FpgaEn: bit'(0),  // for Xilinx and Altera
      FpgaAlteraEn: bit'(0),  // for Altera (only)
      TechnoCut: bit'(0),
      SuperscalarEn: bit'(0),
      NrCommitPorts: unsigned'(CVA6ConfigNrCommitPorts),
      AxiAddrWidth: unsigned'(CVA6ConfigAxiAddrWidth),
      AxiDataWidth: unsigned'(CVA6ConfigAxiDataWidth),
      AxiIdWidth: unsigned'(CVA6ConfigAxiIdWidth),
      AxiUserWidth: unsigned'(CVA6ConfigDataUserWidth),
      MemTidWidth: unsigned'(CVA6ConfigMemTidWidth),
      NrLoadBufEntries: unsigned'(CVA6ConfigNrLoadBufEntries),
      RVF: bit'(CVA6ConfigRVF),
      RVD: bit'(CVA6ConfigRVD),
      XF16: bit'(CVA6ConfigF16En),
      XF16ALT: bit'(CVA6ConfigF16AltEn),
      XF8: bit'(CVA6ConfigF8En),
      XF8ALT: bit'(CVA6ConfigF8AltEn),
      RVA: bit'(CVA6ConfigAExtEn),
      RVB: bit'(CVA6ConfigBExtEn),
      ZKN: bit'(0),
      RVV: bit'(CVA6ConfigVExtEn),
      RVC: bit'(CVA6ConfigCExtEn),
      RVH: bit'(CVA6ConfigHExtEn),
      RVZCB: bit'(CVA6ConfigZcbExtEn),
      RVZCMP: bit'(CVA6ConfigZcmpExtEn),
      RVZCMT: bit'(0),
      XFVec: bit'(CVA6ConfigFVecEn),
      CvxifEn: bit'(CVA6ConfigCvxifEn),
      CoproType: config_pkg::COPRO_NONE,
      RVZiCond: bit'(CVA6ConfigRVZiCond),
      RVSCLIC: bit'(CVA6ConfigSclicExtEn),
      RVXHCLIC: bit'(CVA6ConfigXhclicExtEn),
      RVZicntr: bit'(1),
      RVZihpm: bit'(1),
      NrScoreboardEntries: unsigned'(CVA6ConfigNrScoreboardEntries),
      PerfCounterEn: bit'(CVA6ConfigPerfCounterEn),
      MmuPresent: bit'(CVA6ConfigMmuPresent),
      RVS: bit'(1),
      RVU: bit'(1),
      SoftwareInterruptEn: bit'(1),
      HaltAddress: 64'h800,
      ExceptionAddress: 64'h808,
      RASDepth: unsigned'(CVA6ConfigRASDepth),
      BTBEntries: unsigned'(CVA6ConfigBTBEntries),
      BPType: config_pkg::BHT,
      BHTEntries: unsigned'(CVA6ConfigBHTEntries),
      BHTHist: unsigned'(3),
      DmBaseAddress: 64'h0,
      TvalEn: bit'(CVA6ConfigTvalEn),
      DirectVecOnly: bit'(0),
      NrPMPEntries: unsigned'(CVA6ConfigNrPMPEntries),
      PMPCfgRstVal: {64{64'h0}},
      PMPAddrRstVal: {64{64'h0}},
      PMPEntryReadOnly: 64'd0,
      PMPNapotEn: bit'(1),
      NOCType: config_pkg::NOC_TYPE_AXI4_ATOP,
      CLICNumInterruptSrc: unsigned'(256),
      // Memory Regions
      //    NonIdemp Region
      NrNonIdempotentRules: unsigned'(2),
      //                            SoC Periph;        Cluster
      NonIdempotentAddrBase: 1024'({SoCPeriphBase,    ClusterBase  }),
      NonIdempotentLength:   1024'({SoCPeriphLength,  ClusterLength}),
      //    Exe Region
      NrExecuteRegionRules: unsigned'(4),
      //                             WideSPM;       NarrowSPM;    Boot ROM;        Debug Module
      ExecuteRegionAddrBase: 1024'({WideSPMBase,   NarrowSPMBase, BootromBase,    DebugBase  }),
      ExecuteRegionLength:   1024'({WideSPMLength, NarrowSPMBase, BootromLength,  DebugLength}),
      //    Cache Region
      NrCachedRegionRules: unsigned'(2),
      //                             WideSPM;       NarrowSPM
      CachedRegionAddrBase:  1024'({WideSPMBase,   NarrowSPMBase  }),
      CachedRegionLength:    1024'({WideSPMLength, NarrowSPMLength}),
      MaxOutstandingStores: unsigned'(7),
      DebugEn: bit'(1),
      AxiBurstWriteEn: bit'(0),
      IcacheByteSize: unsigned'(CVA6ConfigIcacheByteSize),
      IcacheSetAssoc: unsigned'(CVA6ConfigIcacheSetAssoc),
      IcacheLineWidth: unsigned'(CVA6ConfigIcacheLineWidth),
      DcacheByteSize: unsigned'(CVA6ConfigDcacheByteSize),
      DcacheSetAssoc: unsigned'(CVA6ConfigDcacheSetAssoc),
      DcacheLineWidth: unsigned'(CVA6ConfigDcacheLineWidth),
      DcacheFlushOnFence: unsigned'(CVA6ConfigDcacheFlushOnFence),
      DcacheInvalidateOnFlush: unsigned'(CVA6ConfigDcacheInvalidateOnFlush),
      DataUserEn: unsigned'(CVA6ConfigDataUserEn),
      WtDcacheWbufDepth: int'(CVA6ConfigWtDcacheWbufDepth),
      FetchUserWidth: unsigned'(CVA6ConfigFetchUserWidth),
      FetchUserEn: unsigned'(CVA6ConfigFetchUserEn),
      DCacheType: CVA6ConfigDcacheType,
      InstrTlbEntries: int'(16),
      DataTlbEntries: int'(16),
      UseSharedTlb: bit'(0),
      SharedTlbDepth: int'(64),
      NrLoadPipeRegs: int'(CVA6ConfigNrLoadPipeRegs),
      NrStorePipeRegs: int'(CVA6ConfigNrStorePipeRegs),
      DcacheIdWidth: int'(CVA6ConfigDcacheIdWidth)
  };

  localparam config_pkg::cva6_cfg_t CVA6AraConfig = build_config_pkg::build_config(cva6_user_cfg);

  // Define the exception type
  `CVA6_TYPEDEF_EXCEPTION(exception_t, CVA6AraConfig);

  // Standard interface
  `CVA6_INTF_TYPEDEF_ACC_REQ(accelerator_req_t, CVA6AraConfig, fpnew_pkg::roundmode_e);
  `CVA6_INTF_TYPEDEF_ACC_RESP(accelerator_resp_t, CVA6AraConfig, exception_t);

  // MMU interface
  `CVA6_INTF_TYPEDEF_MMU_REQ(acc_mmu_req_t, CVA6AraConfig);
  `CVA6_INTF_TYPEDEF_MMU_RESP(acc_mmu_resp_t, CVA6AraConfig, exception_t);

  // Accelerator - CVA6's top-level interface
  `CVA6_INTF_TYPEDEF_CVA6_TO_ACC(cva6_to_acc_t, accelerator_req_t, acc_mmu_resp_t);
  `CVA6_INTF_TYPEDEF_ACC_TO_CVA6(acc_to_cva6_t, accelerator_resp_t, acc_mmu_req_t);

  cva6_to_acc_t        acc_req;
  acc_to_cva6_t        acc_resp;
  logic                                 acc_resp_valid;
  logic                                 acc_resp_ready;
  logic                                 acc_cons_en;
  logic       [Cva6AraAxiAddrWidth-1:0] inval_addr;
  logic                                 inval_valid;
  logic                                 inval_ready;

  // Pack invalidation interface into acc interface
  acc_to_cva6_t acc_resp_pack;
  always_comb begin : pack_inval
    acc_resp_pack                      = acc_resp;
    acc_resp_pack.acc_resp.inval_valid = inval_valid;
    acc_resp_pack.acc_resp.inval_addr  = inval_addr;
    inval_ready                        = acc_req.acc_req.inval_ready;
    acc_cons_en                        = acc_req.acc_req.acc_cons_en;
  end

  cva6 #(
    .CVA6Cfg           (CVA6AraConfig            ),
    .chip_id_t         (chip_id_t                ),
    .cvxif_req_t       (cva6_to_acc_t            ),
    .cvxif_resp_t      (acc_to_cva6_t            ),
    .axi_ar_chan_t     (cva6_ara_axi_ar_chan_t   ),
    .axi_aw_chan_t     (cva6_ara_axi_aw_chan_t   ),
    .axi_w_chan_t      (cva6_ara_axi_w_chan_t    ),
    .b_chan_t          (cva6_ara_axi_b_chan_t    ),
    .r_chan_t          (cva6_ara_axi_r_chan_t    ),
    .noc_req_t         (cva6_ara_axi_req_t       ),
    .noc_resp_t        (cva6_ara_axi_resp_t      ),
    .accelerator_req_t (accelerator_req_t        ),
    .accelerator_resp_t(accelerator_resp_t       ),
    .acc_mmu_req_t     (acc_mmu_req_t            ),
    .acc_mmu_resp_t    (acc_mmu_resp_t           )
  ) i_ariane (
    .clk_i            (clk_i                   ),
    .rst_ni           (rst_ni                  ),
    .chip_id_i        (chip_id_i               ),
    .boot_addr_i      (cva6_boot_addr          ),
    .hart_id_i        ('0                      ),
    .irq_i            (irq_i                   ),
    .ipi_i            (ipi_i                   ),
    .time_irq_i       (time_irq_i              ),
    .debug_req_i      (debug_req_i             ),
    .clic_irq_valid_i ('0                      ),
    .clic_irq_id_i    ('0                      ),
    .clic_irq_level_i ('0                      ),
    .clic_irq_priv_i  ('0                      ),
    .clic_irq_v_i     ('0                      ),
    .clic_irq_vsid_i  ('0                      ),
    .clic_irq_shv_i   ('0                      ),
    .clic_irq_ready_o (/* empty */             ),
    .clic_kill_req_i  ('0                      ),
    .clic_kill_ack_o  (/* empty */             ),
    .rvfi_probes_o    (/* empty */             ),
    // Offload Interface between CVA6 <-> Ara
    .cvxif_req_o      (acc_req                 ),
    .cvxif_resp_i     (acc_resp_pack           ),
    // AXI Interface
    .noc_req_o        (cva6_axi_req            ),
    .noc_resp_i       (cva6_axi_resp           )
  );


  /////////
  // ARA //
  /////////
  localparam int unsigned             VLEN         = 128;
  localparam int unsigned             OSSupport    = 0;
  localparam ara_pkg::fpu_support_e   FPUSupport   = ara_pkg::FPUSupportSingle;
  localparam ara_pkg::fpext_support_e FPExtSupport = ara_pkg::FPExtSupportDisable;
  localparam ara_pkg::fixpt_support_e FixPtSupport = ara_pkg::FixedPointEnable;
  localparam ara_pkg::seg_support_e   SegSupport   = ara_pkg::SegSupportEnable;


  axi_inval_filter #(
    .MaxTxns    (4                                    ),
    .AddrWidth  (Cva6AraAxiAddrWidth                  ),
    .L1LineWidth(CVA6AraConfig.DCACHE_LINE_WIDTH/8    ),
    .aw_chan_t  (cva6_ara_axi_aw_chan_t               ),
    .req_t      (cva6_ara_axi_req_t                   ),
    .resp_t     (cva6_ara_axi_resp_t                  )
  ) i_axi_inval_filter (
    .clk_i        (clk_i             ),
    .rst_ni       (rst_ni            ),
    .en_i         (acc_cons_en       ),
    .slv_req_i    (ara_axi_req       ),
    .slv_resp_o   (ara_axi_resp      ),
    .mst_req_o    (ara_axi_req_inval ),
    .mst_resp_i   (ara_axi_resp_inval),
    .inval_addr_o (inval_addr        ),
    .inval_valid_o(inval_valid       ),
    .inval_ready_i(inval_ready       )
  );

  ara #(
    .NrLanes           (2                         ),
    .VLEN              (VLEN                      ),
    .OSSupport         (OSSupport                 ),
    .FPUSupport        (FPUSupport                ),
    .FPExtSupport      (FPExtSupport              ),
    .FixPtSupport      (FixPtSupport              ),
    .SegSupport        (SegSupport                ),
    .CVA6Cfg           (CVA6AraConfig             ),
    .exception_t       (exception_t               ),
    .accelerator_req_t (accelerator_req_t         ),
    .accelerator_resp_t(accelerator_resp_t        ),
    .acc_mmu_req_t     (acc_mmu_req_t             ),
    .acc_mmu_resp_t    (acc_mmu_resp_t            ),
    .cva6_to_acc_t     (cva6_to_acc_t             ),
    .acc_to_cva6_t     (acc_to_cva6_t             ),
    .AxiDataWidth      (Cva6AraAxiDataWidth       ),
    .AxiAddrWidth      (Cva6AraAxiAddrWidth       ),
    .axi_ar_t          (cva6_ara_axi_ar_chan_t    ),
    .axi_r_t           (cva6_ara_axi_r_chan_t     ),
    .axi_aw_t          (cva6_ara_axi_aw_chan_t    ),
    .axi_w_t           (cva6_ara_axi_w_chan_t     ),
    .axi_b_t           (cva6_ara_axi_b_chan_t     ),
    .axi_req_t         (cva6_ara_axi_req_t        ),
    .axi_resp_t        (cva6_ara_axi_resp_t       )
  ) i_ara (
    .clk_i           (clk_i         ),
    .rst_ni          (rst_ni        ),
    // Scan Disable
    .scan_enable_i   (1'b0          ),
    .scan_data_i     (1'b0          ),
    .scan_data_o     (/* Unused */  ),
    // Offload Interface between CVA6 <-> Ara
    .acc_req_i       (acc_req       ),
    .acc_resp_o      (acc_resp      ),
    // AXI Interface
    .axi_req_o       (ara_axi_req   ),
    .axi_resp_i      (ara_axi_resp  )
  );




endmodule
