# Copyright 2024 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Yunhao Deng <yunhao.deng@kuleuven.be>

# Run functional regression checks
name: ci
on: [push, pull_request]
jobs:

  ########
  # Docs #
  ########

  # docs:
  #   name: Build documentation
  #   runs-on: ubuntu-22.04
  #   container:
  #     image: ghcr.io/pulp-platform/occamy:main
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build docs
  #       run: |
  #         bender update && bender checkout
  #         mkdocs build

  #######################
  # Build SW for Occamy #
  #######################

  # occamy-sw:
  #   name: Build SW for Occamy
  #   runs-on: ubuntu-22.04
  #   container:
  #     image: ghcr.io/pulp-platform/occamy:main
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: 'recursive'
  #     - name: Build Software
  #       run: |
  #         make -C target/sim sw

  ######################################
  # Occamy System Hardware Compilation #
  ######################################

  occamy-verilator:
    name: Compile Occamy Verilator Binary for behavioral simulation
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/kuleuven-micas/snax:main
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Compile RTL
        run: |
          make rtl CFG_OVERRIDES=target/rtl/cfg/occamy_cfg/snax_two_clusters.hjson
      - name: Compile Verilator Binary
        run: |
          make occamy_system_vlt
