# Copyright 2024 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Yunhao Deng <yunhao.deng@kuleuven.be>

# Run functional regression checks
name: ci
on: [pull_request]
jobs:

  ########
  # Docs #
  ########

  # docs:
  #   name: Build documentation
  #   runs-on: ubuntu-22.04
  #   container:
  #     image: ghcr.io/pulp-platform/occamy:main
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build docs
  #       run: |
  #         bender update && bender checkout
  #         mkdocs build

  #################################################
  # Occamy System Software + Hardware Compilation #
  #################################################

  occamy-verilator:
    name: Compile Occamy Software + Hardware Verilator Binary for behavioral simulation
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/kuleuven-micas/snax:main
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Compile Bootrom
        run: |
          echo -e "The placeholer for compiling Bootrom"
          echo -e "Should execute \"make bootrom\""
      - name: Compile SW
        run: |
          echo -e "The placeholer for compiling SW"
          echo -e "Should execute \"make sw\""
      - name: Compile RTL
        run: |
          make rtl CFG_OVERRIDE=target/rtl/cfg/occamy_cfg/hemaia.hjson
      - name: Compile Verilator Binary
        run: |
          make occamy_system_vlt
